// counter
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

// Wolfram
export const REQUEST_ANSWER = 'REQUEST_ANSWER'
export const RECEIVE_ANSWER = 'RECEIVE_ANSWER'
